// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEuDgvRWzMYRDRAYtasGdmXSpooWtlITM',
    appId: '1:542357172243:web:06282d749f7985cf814fe6',
    messagingSenderId: '542357172243',
    projectId: 'laundry-60f78',
    authDomain: 'laundry-60f78.firebaseapp.com',
    storageBucket: 'laundry-60f78.firebasestorage.app',
    measurementId: 'G-XQC2X38516',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl94NcpnhmYRp--T8EJ7YFQ1YXT01wxZo',
    appId: '1:542357172243:android:6eed4bc757458fd5814fe6',
    messagingSenderId: '542357172243',
    projectId: 'laundry-60f78',
    storageBucket: 'laundry-60f78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRDSMPx3XlURb-NBS7e0_F1QoIKuXZVkU',
    appId: '1:542357172243:ios:45c26cd9ea6d1614814fe6',
    messagingSenderId: '542357172243',
    projectId: 'laundry-60f78',
    storageBucket: 'laundry-60f78.firebasestorage.app',
    androidClientId: '542357172243-4jj7p26hfnjl06t2m100sngevljupdqo.apps.googleusercontent.com',
    iosClientId: '542357172243-cu766ou2kcue503lokagqnal5q3m6cdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectLaundryFlutter',
  );
}
